definitions:
  dto.Odontologo:
    properties:
      apellido:
        type: string
      matricula:
        type: string
      nombre:
        type: string
    required:
    - apellido
    - matricula
    - nombre
    type: object
  web.errorResponse:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  web.response:
    properties:
      data: {}
    type: object
info:
  contact:
    name: API Support
    url: https://developers.ctd.com.ar/support
  description: Esta API permite realizar operaciones CRUD sobre la base de datos del
    consultorio, que contiene registros de odontólogos, pacientes y turnos
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.ctd.com.ar/es_ar/terminos-y-condiciones
  title: API consultorio odontológico
  version: "1.0"
paths:
  /odontologos:
    post:
      description: Crea un nuevo odontólogo
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Odontologo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.Odontologo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: POST odontologo
      tags:
      - Odontologo
  /odontologos/:id:
    delete:
      description: Elimina un odontólogo por su ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Odontologo Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: DELETE odontologo by ID
      tags:
      - Odontologo
    get:
      consumes:
      - application/json
      description: Obtiene un odontólogo por su ID
      parameters:
      - description: Odontologo Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: GET odontologo by ID
      tags:
      - Odontologo
    patch:
      description: Actualizar parcialmente un odontólogo por su ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Odontologo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.Odontologo'
      - description: Odontologo Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: PATCH odontologo by ID
      tags:
      - Odontologo
    put:
      consumes:
      - application/json
      description: Actualiza un odontologo por su ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Odontologo
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.Odontologo'
      - description: Odontologo Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.errorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.errorResponse'
      summary: PUT odontologo by ID
      tags:
      - Odontologo
swagger: "2.0"
